# Generated by Django 5.2.1 on 2025-05-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='predicted_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='true_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
